---

sudo: required
dist: trusty

env:
  global:
    - CONTAINER_IMAGES="images:centos/7 ubuntu:16.04"
  matrix:
    - ANSIBLE_VERSIONS="2.1.6.0"
    - ANSIBLE_VERSIONS="2.2.3.0"
    - ANSIBLE_VERSIONS="latest"

install:
  - ./test.sh install

script:
  - ./test.sh test
