FROM centos:6
MAINTAINER Stefan Berggren <nsg@nsg.cc>
RUN yum -y install openssh-server curl sudo
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
RUN sed -i '/Defaults.*requiretty/d' /etc/sudoers
RUN curl -L https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub > /root/.ssh/authorized_keys \
	&& chmod 600 /root/.ssh/authorized_keys
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key \
	&& ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
CMD /usr/sbin/sshd -p 2222 -D
